[package]
edition = "2021"
name = "scrollrack-gui"
version = "0.1.0"
[dependencies]
dioxus = "*"
dioxus-desktop = "0.3.0"
itertools = "0.10.3"

[dependencies.scrollrack-core]
path = "../scrollrack-core"
